[package]
name = "pathsearch"
version = "0.2.2"
edition = "2024"

[dependencies]
regex = { version = "1", default-features = false, features = ["std", "unicode-perl"] }

[profile.release]
lto = true
opt-level = "z"
strip = true
