[package]
name = "pathsearch"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = { version = "1", default-features = false, features = ["std", "unicode-perl"] }
